### PR TITLE
DNET-570 Loading error messages from a manifest resource fails on mono

### PR DESCRIPTION
**Pull request by mrgleba**
Added a call to ResourceSet.GetEnumerator to initializa the ResourceSet
Added caching of ResourceSets

### CODE REVIEW

**Comment by cincuranet** [comment]
HI, do you have any measurements about caching the `ResourceSet`? I like the idea, although I don't want to have unnecessary objects in memory for long time for not real benefit.

**Comment by mrgleba** [comment]
Hi!

My reasoning is that memory is pretty abundant and IO is expensive.
There are about 1000 records in each: is_error_msg and sql_state_mapping.
It seems the cache would take circa 100kb in mem, which IMHO is acceptable.

Alternatively the cache could be encapsulated in a WeakReference soas to
get GCed when mem becomes scarce.

Cheers!
Michał




2015-01-13 8:53 GMT+01:00 Jiri {x2} Cincura <notifications@github.com>:

**Comment by cincuranet** [comment]
Just thinking... Maybe it's worth to just create two static hashtables (one for each resource) and remove the resources whatsoever. It will be in the code. Immediately available. No need to fiddle with resources.

That might be even better, don't you think?

**Comment by mrgleba** [comment]
Makes complete sense for sql_state_mapping.
As for error messages I wouldn't change it in order to enable localizations
in the future

Cheers!
Michał

2015-01-13 14:34 GMT+01:00 Jiri {x2} Cincura <notifications@github.com>:

**Comment by cincuranet** [comment]
Good point. But in last 5+ years nobody did anything about localization of messages. And `firebird.msg` is kept in English anyway. 

I'll give it a day to think about and we'll see.

**Comment by mrgleba** [comment]
>
> Good point. But in last 5+ years nobody did anything about localization of
> messages. And firebird.msg is kept in English anyway.
>
Still it'd be good to have the possibility. The cost of loading it to the
cache from resources once is negligeble.

>
Cheers

**Comment by cincuranet** [comment]
Hi. So I made some changes. I decided to make it all static. When the translation comes and somebody will be willing to keep it updated (I highly doubt that's going to happen), I might change it.

Can you have a look at [this branch](https://github.com/cincuranet/NETProvider/tree/resources)? If it looks good, I'll merge it and release.

[Here](https://ci.appveyor.com/project/cincura_net/netprovider/build/0.0.0.141)'s the - curently latest - build of that branch.

**Comment by mrgleba** [comment]
Hi!

> Can you have a look at this branch
> <https://github.com/cincuranet/NETProvider/tree/resources>? If it looks
> good, I'll merge it and release.
>
I'd use TryGet in accesing SqlStateMapping. Apart from that the change
seems fine.

Cheers!
Michal

**Comment by cincuranet** [comment]
Why?

**Comment by mrgleba** [comment]
We'd get an exception in there in case we recieve an unknown error code.

2015-01-21 8:53 GMT+01:00 Jiri {x2} Cincura <notifications@github.com>:

**Comment by cincuranet** [comment]
No. You would not. See [this](https://github.com/cincuranet/NETProvider/blob/resources/NETProvider/src/FirebirdSql.Data.FirebirdClient/Common/IscException.cs#L197). It's calling the [`GetValueOrDefault`](https://github.com/cincuranet/NETProvider/blob/resources/NETProvider/src/FirebirdSql.Data.FirebirdClient/Common/IscException.cs#L284) helper.

**Comment by mrgleba** [comment]
You're right.
I was looking at your initial commit rather than the final result.
That's why you shouldn't answer e-mails before your morning coffee :)

Everything looks fine.

Cheers
Michał

2015-01-21 9:02 GMT+01:00 Jiri {x2} Cincura <notifications@github.com>:

**Comment by cincuranet** [comment]
Good, I'll run the test suite and merge.

**Comment by cincuranet** [comment]
Reworked into PR #22.

**Comment by mrgleba** [comment]
Great!
Thank you.

2015-01-23 8:13 GMT+01:00 Jiri {x2} Cincura <notifications@github.com>:

**Comment by cincuranet** [comment]
I'll try to release new version in few days.

**Pull request closed without merging**
